#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar (custom configuration in ~/.config/waybar)
waybar &
# $scripts/launch_waybar &
# $scripts/tools/dynamic &

# wallpaper
$scripts/wall $HOME/Pictures/Sys/bg/wallpaper1.jpg &

# for chinese and japanese inputs, using fcitx5
fcitx5 -d

# for disk automount and tray icon
udiskie --tray &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
